[package]
name = "sierra-compile-json"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intemediate representation - Outputs a serialized JSON"

[dependencies]
anyhow.workspace = true
log.workspace = true
clap.workspace = true
indoc.workspace = true
serde_json.workspace = true

cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "2.5.4" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "2.5.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.4", features = [
    "env_logger",
] }